import { ImgFullScreenProps } from "@components/commons/ImageFullScreen";

export const carousel1: ImgFullScreenProps[] = [
  {
    src: "/Gallery/Illustration/0001.jpg",
    alt: "Walk in The Mountain",
    title: "Walk in The Mountain",
    text: "Inspired by the landscapes of the Alps, I depicted my favorite characters strolling through the mountains, experimenting with new techniques, colors, and brush textures to capture the tranquil atmosphere.",
    source: "Doodle / 2021",
  },
  {
    src: "/Gallery/Illustration/0002.jpg",
    alt: "Seasonal Soundscapes",
    title: "Seasonal Soundscapes",
    text: "Would you transition your music playlist from winter to spring? How does the vibe change for you during this transition?",
    source: "The Daily Texan / 2023",
  },
  {
    src: "/Gallery/Illustration/0003.jpg",
    alt: "My Tennis Partner: The Wall",
    title: "My Tennis Partner: The Wall",
    text: "The wall is your best companion when playing tennis alone. It mirrors your movements, requiring you to adapt dynamically. If you find yourself without a playing partner, don't be disheartened; seek out a wall and enhance your skills!",
    source: "Doodle / 2018",
  },
  {
    src: "/Gallery/Illustration/0004.jpg",
    alt: "Best Halloween Costume",
    title: "Best Halloween Costume",
    text: "What should I dress up as for the costume party? Using some tissue paper to turn myself into a mummy, and adding a dollop of ketchup did the trick, giving my look just the right amount of fright!",
    source: "Halloween Card / 2021",
  },
  {
    src: "/Gallery/Illustration/0005.jpg",
    alt: "Happy Earth Day",
    title: "Happy Earth Day",
    text: "An Illustration for the 2022 Earth Day.",
    source: "The Daily Texan/ 2022",
  },
  {
    src: "/Gallery/Illustration/0006.jpg",
    alt: "2022 Beijing Winter Olympics",
    title: "2022 Beijing Winter Olympics",
    text: "Watch the 2022 Beijing Winter Olympics and discuss it with your friends!",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0007.jpg",
    alt: "Body Image Pressures",
    title: "Body Image Pressures",
    text: "The issue of appearance anxiety among contemporary women is growing increasingly concerning, particularly regarding body image. The prevalence of body shaming culture on social media exacerbates this toxicity. This illustration serves to depict the anxiety experienced by women in response to these societal pressures.",
    source: "The Daily Texan / 2023",
  },
  {
    src: "/Gallery/Illustration/0008.jpg",
    alt: "2023 Shiba New Year Card",
    title: "2023 Shiba New Year Card",
    text: `Influenced by the homophonic connection between the Shiba Inu breed and the Chinese word for "wealth," I illustrated our Shiba Inu adorned with a headdress featuring rabbit ears, symbolizing the Year of the Rabbit.`,
    source: "Card Design / 2023",
  },
  {
    src: "/Gallery/Illustration/0009.jpg",
    alt: "My working BGM",
    title: "My working BGM",
    text: "Listening to music while working is always a great companion. It can be motivating and has the power to shift your mood.",
    source: "Doodle / 2023",
  },
  {
    src: "/Gallery/Illustration/0010.jpg",
    alt: "The Interconnectedness of Mental and Physical Health",
    title: "The Interconnectedness of Mental and Physical Health",
    text: "Illustrate a study discussing how mental health can affect physical health, as they are correlated with each other.",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0011.jpg",
    alt: "International Bridge",
    title: "International Bridge",
    text: "Drawing how international students bond with each other, finding solace in shared experiences of being far from home, loneliness, culture shock, and language barriers. These shared struggles create strong connections among them.",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0012.jpg",
    alt: "Exposing BevoPay",
    title: "Exposing BevoPay",
    text: "Illustration for an article highlighting technical issues with UT's payment system, BevoPay, and its impact on the overall customer experience.",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0013.jpg",
    alt: "Boiling Water Notice",
    title: "Boiling Water Notice",
    text: "Illustration for an article discussing the boiled water notice in Austin and its impact on daily life.",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0014.jpg",
    alt: "International Students Community",
    title: "International Students Community",
    text: "Illustration depicting how international students build their own community, forge strong bonds, and make friends across different nationalities.",
    source: "The Daily Texan / 2022",
  },
];

export const carousel2: ImgFullScreenProps[] = [
  {
    src: "/Gallery/Illustration/0015.jpg",
    alt: "Cool Food",
    title: "Cool Food",
    text: "Introducing the concept of cool food and how it can benefit not only ourselves but also the ecosystem and climate change.",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0016.jpg",
    alt: "Embrace the LOVE",
    title: "Embrace the LOVE",
    text: "On a frustrated night, I posted an Instagram story to express my emotions. Later, I was filled with love in response and drew this illustration. I want to embrace all this love.",
    source: "Doodle / 2021",
  },
  {
    src: "/Gallery/Illustration/0017.jpg",
    alt: "Happy Rabbit Year!",
    title: "Happy Rabbit Year!",
    text: "It was illustrated to celebrate the 2023 Rabbit Year in the Zodiac! In our culture, dumplings symbolize fortune and good luck for wealth in the upcoming year!",
    source: "Card Design / 2023",
  },
  {
    src: "/Gallery/Illustration/0018.jpg",
    alt: "Let’s Play Tennis!",
    title: "Let’s Play Tennis!",
    text: "While designing my personal website, I wanted to capture the essence of my college life. Since the tennis club played a significant role during my time in college, I created this initial illustration to reflect that important part of my journey.",
    source: "Website Use / 2020",
  },
  {
    src: "/Gallery/Illustration/0019.jpg",
    alt: "Pumpkin Dog",
    title: "Pumpkin Dog",
    text: "This is one of the Halloween card I designed for 2021. Can my dog also have his own costume? I think he already found it!",
    source: "Halloween Card / 2021",
  },
  {
    src: "/Gallery/Illustration/0020.jpg",
    alt: "Woof Birthday",
    title: "Woof Birthday",
    text: "I drew this cute Shiba Inu for my friend’s birthday. Since it was a winter day, I made sure to give him a cozy scarf to wear.",
    source: "Birthday Card / 2020",
  },
  {
    src: "/Gallery/Illustration/0021.jpg",
    alt: "A Journey Abroad",
    title: "A Journey Abroad",
    text: "Just like a penguin leaving its home, I decided to study abroad. This next step marks the beginning of new challenges and adventures.",
    source: "Doodle / 2021",
  },
  {
    src: "/Gallery/Illustration/0022.jpg",
    alt: "Giving Helping Hands",
    title: "Giving Helping Hands",
    text: "As international students, we all face language and cultural barriers. What we need is a helping hand, regardless of race.",
    source: "The Daily Texan / 2023",
  },
  {
    src: "/Gallery/Illustration/0023.jpg",
    alt: "Sensorable Head Band",
    title: "Sensorable Head Band",
    text: "It depicts the story of mechatronics engineering students developing innovative sensors to monitor physical and mental states.",
    source: "The Daily Texan / 2023",
  },
  {
    src: "/Gallery/Illustration/0024.jpg",
    alt: "Pride Month",
    title: "Pride Month",
    text: "Celebrate Pride Month, embracing all races, genders, and diverse sexualities. Be proud!",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0025.jpg",
    alt: "Adrift in Alaska",
    title: "Adrift in Alaska",
    text: "Flight got cancelled, I found myself wandering in Alaska. I sat on a ferry, drifting with the waves, uncertain of my destination. This painting captures that moment.",
    source: "Doodle / 2023",
  },
  {
    src: "/Gallery/Illustration/0026.jpg",
    alt: "Angel Domino",
    title: "Angel Domino",
    text: "In Memory of UT's Beloved Campus Cat, Domino. We cherished our time with you on campus. Rest in peace and be a happy angel!",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0027.jpg",
    alt: "The Daily Texan Broadcaster",
    title: "The Daily Texan Broadcaster",
    text: "Documenting students working on UT’s The Daily Texan broadcast",
    source: "The Daily Texan / 2022",
  },
];
