import { ImgFullScreenProps } from "@components/commons/ImageFullScreen";

export const carousel1: ImgFullScreenProps[] = [
  {
    src: "/Gallery/Illustration/0001.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0002.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0003.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0004.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0005.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0006.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0007.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0008.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0009.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0010.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0011.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0012.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0013.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0014.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
];

export const carousel2: ImgFullScreenProps[] = [
  {
    src: "/Gallery/Illustration/0015.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0016.jpg",
    alt: "Embrace the LOVE",
    title: "Embrace the LOVE",
    text: "On a frustrated night, I posted an Instagram story to express my emotions. Later, I was filled with love in response and drew this illustration. I want to embrace all this love.",
    source: "Doodle / 2021",
  },
  {
    src: "/Gallery/Illustration/0017.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0018.jpg",
    alt: "Let’s Play Tennis!",
    title: "Let’s Play Tennis!",
    text: "While designing my personal website, I wanted to capture the essence of my college life. Since the tennis club played a significant role during my time in college, I created this initial illustration to reflect that important part of my journey.",
    source: "Website Use / 2020",
  },
  {
    src: "/Gallery/Illustration/0019.jpg",
    alt: "Pumpkin Dog",
    title: "Pumpkin Dog",
    text: "This is one of the Halloween card I designed for 2021. Can my dog also have his own costume? I think he already found it!",
    source: "Halloween Card / 2021",
  },
  {
    src: "/Gallery/Illustration/0020.jpg",
    alt: "Woof Birthday",
    title: "Woof Birthday",
    text: "I drew this cute Shiba Inu for my friend’s birthday. Since it was a winter day, I made sure to give him a cozy scarf to wear.",
    source: "Birthday Card / 2020",
  },
  {
    src: "/Gallery/Illustration/0021.jpg",
    alt: "A Journey Abroad",
    title: "A Journey Abroad",
    text: "Just like a penguin leaving its home, I decided to study abroad. This next step marks the beginning of new challenges and adventures.",
    source: "Doodle / 2021",
  },
  {
    src: "/Gallery/Illustration/0022.jpg",
    alt: "Giving Helping Hands",
    title: "Giving Helping Hands",
    text: "As international students, we all face language and cultural barriers. What we need is a helping hand, regardless of race.",
    source: "The Daily Texan / 2023",
  },
  {
    src: "/Gallery/Illustration/0023.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0024.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0025.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0026.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
  {
    src: "/Gallery/Illustration/0027.jpg",
    alt: "The Daily Texan Broadcaster",
    title: "The Daily Texan Broadcaster",
    text: "Documenting students working on UT’s The Daily Texan broadcast",
    source: "The Daily Texan / 2022",
  },
  {
    src: "/Gallery/Illustration/0028.jpg",
    alt: "",
    title: "",
    text: "",
    source: "",
  },
];
